### PR TITLE
[LoginViewController] Refactor, Runs Successfully

### PR DESCRIPTION
**Pull request by mmrtnz**
**`WeavedAPIManager`**
- New endpoint for route `device/list/all`

**`SimpleHttpRequest`**
- Updates API managers to handle response data

**`LoginViewController`**
- Removes devices table view (code commented out)
- Login button uses `WeavedAPIManager`
- `listDevices()` uses `WeavedAPIManager` (outputted to console)

### CODE REVIEW

**Review by VictorAny — APPROVED** [review]
Looks good.

Thoughts on having the WeavedAPIManager a property of the VC? To reduce the instantiations?

**Comment by mmrtnz** [comment]
That's a good idea. When all our VCs are finalized we could have a single WeavedApiManager for the entire app.

**Comment by VictorAny** [comment]
Like a singleton?

**Comment by mmrtnz** [comment]
Yeah 👍👍👍

**Pull request merged**
