### PR TITLE
[PinSetupViewController] Adds custom view to configure pi and other UI changes

### PR DESCRIPTION
**Pull request by mmrtnz**
- The UI is updated to **_show_** all functionality (see images below)
  - Includes improving the navigation bar
- A GPIO diagram is created programmatically

Navbar changes
screen shot 2017-03-21 at 11 53 24 pm
screen shot 2017-03-21 at 11 56 19 pm

`Storyboard`
image

Device Setup Scene for templates 
pi-setup-1

### CODE REVIEW

**Comment by VictorAny** [comment]
Looking good!

**Comment by mmrtnz** [comment]
@VictorAny This PR is ready for review. Things are connected to begin working on persisting `template` data.

**Comment by VictorAny** [comment]
I think its ready to merge. Anything else to add @mmrtnz?

**Comment by mmrtnz** [comment]
This pr is all set @VictorAny

**Comment by VictorAny** [comment]
Dope

**Pull request merged**
